"""
RAG Evaluation Suite using RAGAS framework.

Measures 4 metrics:
- Faithfulness: is the answer supported by retrieved context?
- Answer Relevancy: does the answer address the question?
- Context Recall: did retrieval find the right chunks?
- Context Precision: were retrieved chunks actually relevant?

Usage: python scripts/evaluate_rag.py
"""
import sys
import os
import asyncio
import re
import time

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

print("Starting evaluation script...")

from dotenv import load_dotenv
load_dotenv()

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_recall,
    context_precision
)
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.embeddings import SentenceTransformerEmbeddings
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

from app.services.langchain_service import ask_with_rag
from app.services.advanced_rag import advanced_rag_search
from app.services.embeddings import search_documents
from app.config import settings
from scripts.evaluation_dataset import EVALUATION_DATASET


def _parse_retry_wait(error_msg: str, default: float = 60.0) -> float:
    """Extract wait time in seconds from a Groq 429 error message."""
    m = re.search(r"try again in\s+([\d]+)m([\d.]+)s", str(error_msg))
    if m:
        return int(m.group(1)) * 60 + float(m.group(2))
    m = re.search(r"try again in\s+([\d.]+)s", str(error_msg))
    if m:
        return float(m.group(1))
    return default


async def _call_with_retry(coro_fn, *args, max_retries: int = 3, **kwargs):
    """Call an async function, retrying on 429 rate-limit errors."""
    for attempt in range(max_retries + 1):
        try:
            return await coro_fn(*args, **kwargs)
        except Exception as e:
            if "429" in str(e) or "rate_limit" in str(e).lower():
                wait = _parse_retry_wait(e)
                print(f"  Rate limit hit. Waiting {wait:.0f}s before retry {attempt+1}/{max_retries}...")
                await asyncio.sleep(wait + 5)  # small buffer
                if attempt == max_retries:
                    raise
            else:
                raise


async def collect_rag_results(dataset: list,
                               use_advanced: bool = False) -> dict:
    """
    Run all questions through the RAG pipeline and collect:
    - questions
    - answers (generated by LLM)
    - contexts (retrieved chunks)
    - ground_truths (expected answers)
    """
    questions = []
    answers = []
    contexts = []
    ground_truths = []

    print(f"\nRunning {'advanced' if use_advanced else 'basic'} RAG evaluation...")
    print(f"Questions to evaluate: {len(dataset)}\n")

    for i, item in enumerate(dataset):
        question = item["question"]
        ground_truth = item["ground_truth"]

        print(f"[{i+1}/{len(dataset)}] {question[:60]}...")

        try:
            if use_advanced:
                # use advanced RAG with hybrid search + reranking
                docs = await _call_with_retry(
                    advanced_rag_search,
                    query=question,
                    n_candidates=10,
                    final_results=3
                )
                retrieved_contexts = [doc["text"] for doc in docs]

                # generate answer using retrieved contexts
                result = await _call_with_retry(
                    ask_with_rag,
                    question=question,
                    n_results=3
                )
            else:
                # use basic RAG
                result = await _call_with_retry(
                    ask_with_rag,
                    question=question,
                    n_results=3
                )

                # get contexts from basic search
                basic_docs = search_documents(
                    query=question,
                    n_results=3
                )
                retrieved_contexts = [doc["text"] for doc in basic_docs]

            questions.append(question)
            answers.append(result["answer"])
            contexts.append(retrieved_contexts)
            ground_truths.append(ground_truth)

        except Exception as e:
            print(f"  Error on question {i+1}: {e}")
            questions.append(question)
            answers.append("Error generating answer")
            contexts.append([""])
            ground_truths.append(ground_truth)

        # small pause between questions to stay within per-minute limits
        if i < len(dataset) - 1:
            await asyncio.sleep(2)

    return {
        "question": questions,
        "answer": answers,
        "contexts": contexts,
        "ground_truth": ground_truths
    }


def run_ragas_evaluation(data: dict) -> dict:
    print("\nRunning RAGAS scoring...")

    dataset = Dataset.from_dict(data)

    # use Gemini instead of Groq for evaluation
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.0-flash",
        google_api_key=os.getenv("GEMINI_API_KEY"),
        temperature=0
    )

    embeddings = SentenceTransformerEmbeddings(
        model_name="all-MiniLM-L6-v2"
    )

    ragas_llm = LangchainLLMWrapper(llm)
    ragas_embeddings = LangchainEmbeddingsWrapper(embeddings)

    result = evaluate(
        dataset=dataset,
        metrics=[faithfulness, answer_relevancy, context_recall, context_precision],
        llm=ragas_llm,
        embeddings=ragas_embeddings,
        raise_exceptions=False,
        is_async=False
    )

    return result


def print_results(result, label: str) -> dict:
    """Print evaluation results in a readable format."""
    print(f"\n{'='*55}")
    print(f"RAGAS Results — {label}")
    print(f"{'='*55}")

    scores = {
        "Faithfulness":      float(result["faithfulness"]),
        "Answer Relevancy":  float(result["answer_relevancy"]),
        "Context Recall":    float(result["context_recall"]),
        "Context Precision": float(result["context_precision"])
    }

    for metric, score in scores.items():
        filled = int(score * 20)
        bar = "█" * filled + "░" * (20 - filled)
        print(f"{metric:<22} {bar}  {score:.3f}")

    avg = sum(scores.values()) / len(scores)
    print(f"\nOverall Average:       {avg:.3f}")
    print(f"{'='*55}")

    return scores


async def compare_pipelines():
    print("\n" + "="*55)
    print("RAG Pipeline Evaluation — RAGAS")
    print("="*55)

    # evaluate basic RAG only first
    basic_data = await collect_rag_results(
        EVALUATION_DATASET,
        use_advanced=False
    )
    basic_results = run_ragas_evaluation(basic_data)
    basic_scores = print_results(basic_results, "Basic RAG")


if __name__ == "__main__":
    asyncio.run(compare_pipelines())